config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  get '/feed', to: 'static#feed'
  get '/api' => redirect('/swagger/dist/index.html?url=/api-docs.json')

  resources :workers
  resources :customers
  resources :create_carts_products
  resources :carts
  resources :products
  resources :orders
  root to: 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/create_carts_product.rb
class CreateCartsProduct < ApplicationRecord
end

app/controllers/create_carts_products_controller.rb
class CreateCartsProductsController < ApplicationController
  before_action :set_create_carts_product, only: [:show, :edit, :update, :destroy]

  # GET /create_carts_products
  # GET /create_carts_products.json
  def index
    @create_carts_products = CreateCartsProduct.all
  end

  # GET /create_carts_products/1
  # GET /create_carts_products/1.json
  def show
  end

  # GET /create_carts_products/new
  def new
    @create_carts_product = CreateCartsProduct.new
  end

  # GET /create_carts_products/1/edit
  def edit
  end

  # POST /create_carts_products
  # POST /create_carts_products.json
  def create
    @create_carts_product = CreateCartsProduct.new(create_carts_product_params)

    respond_to do |format|
      if @create_carts_product.save
        format.html { redirect_to @create_carts_product, notice: 'Create carts product was successfully created.' }
        format.json { render :show, status: :created, location: @create_carts_product }
      else
        format.html { render :new }
        format.json { render json: @create_carts_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /create_carts_products/1
  # PATCH/PUT /create_carts_products/1.json
  def update
    respond_to do |format|
      if @create_carts_product.update(create_carts_product_params)
        format.html { redirect_to @create_carts_product, notice: 'Create carts product was successfully updated.' }
        format.json { render :show, status: :ok, location: @create_carts_product }
      else
        format.html { render :edit }
        format.json { render json: @create_carts_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /create_carts_products/1
  # DELETE /create_carts_products/1.json
  def destroy
    @create_carts_product.destroy
    respond_to do |format|
      format.html { redirect_to create_carts_products_url, notice: 'Create carts product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_create_carts_product
      @create_carts_product = CreateCartsProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_carts_product_params
      params.require(:create_carts_product).permit(:quantity)
    end
end

app/helpers/create_carts_products_helper.rb
module CreateCartsProductsHelper
end

app/views/create_carts_products/_form.html.erb
<%= form_with(model: create_carts_product, local: true) do |form| %>
  <% if create_carts_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(create_carts_product.errors.count, "error") %> prohibited this create_carts_product from being saved:</h2>

      <ul>
      <% create_carts_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :create_carts_product_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/create_carts_products/edit.html.erb
<h1>Editing Create Carts Product</h1>

<%= render 'form', create_carts_product: @create_carts_product %>

<%= link_to 'Show', @create_carts_product %> |
<%= link_to 'Back', create_carts_products_path %>

app/views/create_carts_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Create Carts Products</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @create_carts_products.each do |create_carts_product| %>
      <tr>
        <td><%= create_carts_product.quantity %></td>
        <td><%= link_to 'Show', create_carts_product %></td>
        <td><%= link_to 'Edit', edit_create_carts_product_path(create_carts_product) %></td>
        <td><%= link_to 'Destroy', create_carts_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Create Carts Product', new_create_carts_product_path %>

app/views/create_carts_products/new.html.erb
<h1>New Create Carts Product</h1>

<%= render 'form', create_carts_product: @create_carts_product %>

<%= link_to 'Back', create_carts_products_path %>

app/views/create_carts_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @create_carts_product.quantity %>
</p>

<%= link_to 'Edit', edit_create_carts_product_path(@create_carts_product) %> |
<%= link_to 'Back', create_carts_products_path %>